notifications:
  email: false

matrix:

  include:

    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=alphacep/kaldi-manylinux:latest
           PLAT=manylinux2010_x86_64
      install:
        - docker pull $DOCKER_IMAGE
      script:
        - docker run --rm -e PLAT=$PLAT -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build-wheels.sh
        - ls wheelhouse/

    - os: windows
      language: shell
      before_install:
       - choco install python3 --no-progress -y --version 3.6.8 
       - choco install cmake   --no-progress -y --installargs 'ADD_CMAKE_TO_PATH=System'
       - choco install swig    --no-progress -y
       - C:\\Python36\\python -m pip install --upgrade pip wheel setuptools
      script:
       - cd python
       - C:\\Python36\\python setup.py bdist_wheel
