notifications:
  email: false

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=alphacep/kaldi-manylinux:latest
           PLAT=manylinux2010_x86_64
    - os: windows
      language: shell
      before_install:
       - choco install python3 --version 3.6.8 --no-progress -y
      script:
       - cd python
       - C:\\Python36\\python setup.py bdist_wheel

install:
  - docker pull $DOCKER_IMAGE

script:
  - docker run --rm -e PLAT=$PLAT -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build-wheels.sh
  - ls wheelhouse/
